# --- Pairs List for Matching Game ---
matching_pairs = [
    {"id": 1, "left": "kedi", "right": "cat"},
    {"id": 2, "left": "köpek", "right": "dog"},
    {"id": 3, "left": "kuş", "right": "bird"},
    {"id": 4, "left": "balık", "right": "fish"},
    {"id": 5, "left": "inek", "right": "cow"},
    {"id": 6, "left": "at", "right": "horse"},
    {"id": 7, "left": "tavuk", "right": "chicken"},
    {"id": 8, "left": "ördek", "right": "duck"},
    {"id": 9, "left": "elma", "right": "apple"},
    {"id": 10, "left": "muz", "right": "banana"},
    {"id": 11, "left": "portakal", "right": "orange"},
    {"id": 12, "left": "ekmek", "right": "bread"},
    {"id": 13, "left": "su", "right": "water"},
    {"id": 14, "left": "süt", "right": "milk"},
    {"id": 15, "left": "araba", "right": "car"},
    {"id": 16, "left": "otobüs", "right": "bus"},
    {"id": 17, "left": "tren", "right": "train"},
    {"id": 18, "left": "uçak", "right": "plane"},
    {"id": 19, "left": "ev", "right": "house"},
    {"id": 20, "left": "okul", "right": "school"},
    {"id": 21, "left": "masa", "right": "table"},
    {"id": 22, "left": "sandalye", "right": "chair"},
    {"id": 23, "left": "kitap", "right": "book"},
    {"id": 24, "left": "kalem", "right": "pencil"},
    {"id": 25, "left": "top", "right": "ball"},
    {"id": 26, "left": "güneş", "right": "sun"},
    {"id": 27, "left": "ay", "right": "moon"},
    {"id": 28, "left": "ağaç", "right": "tree"},
    {"id": 29, "left": "çiçek", "right": "flower"},
    {"id": 30, "left": "deniz", "right": "sea"},
]


# --- Memory Game Pairs ---
memory_pairs = [
    {"id": 1, "word": "elma", "image": "apple.jpeg"},
    {"id": 2, "word": "top", "image": "ball.jpeg"},
    {"id": 3, "word": "muz", "image": "banana.jpeg"},
    {"id": 4, "word": "kuş", "image": "bird.png"},
    {"id": 5, "word": "kitap", "image": "book.jpeg"},
    {"id": 6, "word": "ekmek", "image": "bread.jpeg"},
    {"id": 7, "word": "otobüs", "image": "bus.jpeg"},
    {"id": 8, "word": "araba", "image": "car.jpeg"},
    {"id": 9, "word": "kedi", "image": "cat.png"},
    {"id": 10, "word": "sandalye", "image": "char.jpeg"},
    {"id": 11, "word": "tavuk", "image": "chicken.jpeg"},
    {"id": 12, "word": "inek", "image": "cow.jpeg"},
    {"id": 13, "word": "köpek", "image": "dog.png"},
    {"id": 14, "word": "ördek", "image": "duck.jpeg"},
    {"id": 15, "word": "balık", "image": "fish.jpeg"},
    {"id": 16, "word": "çiçek", "image": "flower.jpeg"},
    {"id": 17, "word": "at", "image": "horse.jpeg"},
    {"id": 18, "word": "ev", "image": "house.jpeg"},
    {"id": 19, "word": "süt", "image": "milk.jpeg"},
    {"id": 20, "word": "ay", "image": "moon.jpeg"},
    {"id": 21, "word": "portakal", "image": "orange.jpeg"},
    {"id": 22, "word": "kalem", "image": "pencil.jpeg"},
    {"id": 23, "word": "uçak", "image": "plane.jpeg"},
    {"id": 24, "word": "okul", "image": "school.jpeg"},
    {"id": 25, "word": "deniz", "image": "sea.jpg"},
    {"id": 26, "word": "güneş", "image": "sun.jpeg"},
    {"id": 27, "word": "masa", "image": "table.jpeg"},
    {"id": 28, "word": "tren", "image": "train.jpeg"},
    {"id": 29, "word": "ağaç", "image": "tree.jpeg"},
    {"id": 30, "word": "su", "image": "water.jpeg"},
]